name: Upload Cucumber Reports

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  upload-reports:
    runs-on: ubuntu-latest  # O el sistema que prefieras

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload Cucumber Reports
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: build/reports/cucumber-report.json  # Cambia esta ruta por la ubicación de tu reporte
